# -*- coding: utf-8 -*-
"""visualizacion_de_datos_con_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hin_cZXFeZ5BFiEn78CsQxRcQIrwZsaG

# **Visualizacion de datos con Python: Matplotlib, Seaborn y Plotly**
"""

import pandas as pd

df = pd.read_csv('/content/inmigrantes_canada.csv')

df

df.shape

df.info()

df.set_index('Pais', inplace=True)
df

anos = list(map(str, range(1980, 2014)))
anos

colombia = df.loc['Colombia', anos]
colombia

col_dict = {'Año' :colombia.index.tolist(),
            'Inmigrantes': colombia.values.tolist()}

datos_col = pd.DataFrame(col_dict)
datos_col

"""## **Matplotlib**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4)) #las medidas son en pulgadas
plt.plot(datos_col['Año'], datos_col['Inmigrantes'])
plt.xticks(['1980','1985', '1990', '1995', '2000', '2005', '2010'])
plt.show()

plt.figure(figsize=(8,4)) #las medidas son en pulgadas
plt.plot(datos_col['Año'], datos_col['Inmigrantes'])
plt.xticks(['1980','1985', '1990', '1995', '2000', '2005', '2010'])
plt.title('Inmigración de colombianos hacia Canadá')
plt.xlabel('Años')
plt.ylabel('Número de inmigrantes')
plt.show() #tiene que ser el último comando, lo colocado después de esto, no se visualiza

df

fig, ax = plt.subplots(figsize=(8,4))
ax.plot(datos_col['Año'], datos_col['Inmigrantes'])
ax.xaxis.set_major_locator(plt.MultipleLocator(5)) #el realizar esto es lo mismo que el código anterior =  plt.xticks(['1980','1985', '1990', '1995', '2000', '2005', '2010'])
ax.set_title('Inmigración de colombianos hacia Canadá\n1980 - 2013') #el \n funciona como un "Enter" dentro del str que se esté colocando
ax.set_xlabel('Años')
ax.set_ylabel('Número de inmigrantes')
plt.show()

fig, axs = plt.subplots(1,2, figsize=(10,3))

axs[0].plot(datos_col['Año'], datos_col['Inmigrantes'])
axs[0].set_title('Inmigración de colombianos hacia Canadá\n1980 - 2013') #el \n funciona como un "Enter" dentro del str que se esté colocando
axs[0].set_xlabel('Años')
axs[0].set_ylabel('Número de inmigrantes')
axs[0].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[0].grid()

axs[1].boxplot(datos_col['Inmigrantes'])
axs[1].set_title('Boxplot de la inmigracion de colombianos\nhacia Canadá 1980 - 2013')
axs[1].set_xlabel('Colombia')
axs[1].set_ylabel('Número de inmigrantes')
axs[1].grid()

plt.show()

datos_col.describe()

fig, axs = plt.subplots(2,2, figsize=(10,6))
fig.subplots_adjust(hspace=0.5, wspace=0.3)
fig.suptitle('Inmigracion de los 4 mayores paises sudamericanos\nhacia Canada desde 1980 hasta 2013')

axs[0,0].plot(df.loc['Colombia', anos])
axs[0,0].set_title('Colombia')

axs[0,1].plot(df.loc['Brasil', anos])
axs[0,1].set_title('Brasil')

axs[1,0].plot(df.loc['Argentina', anos])
axs[1,0].set_title('Argentina')

axs[1,1].plot(df.loc['Perú', anos])
axs[1,1].set_title('Perú')

ymin=0
ymax=7000

for ax in axs.ravel():
  ax.set_ylim(ymin,ymax)

#a la hora de utilizar el "for ax in axs.flat:" se entiende que las ordenes que se den,
# se realizaran para todas las graficas dentro del entorno de ejecucion (como esta celda)
for ax in axs.flat:
  ax.xaxis.set_major_locator(plt.MultipleLocator(5))
  ax.set_xlabel('Año')
  ax.set_ylabel('Número de inmigrantes')
  ax.grid()

plt.show()

fig, ax = plt.subplots(figsize=(8,3))
ax.plot(datos_col['Año'], datos_col['Inmigrantes'],lw=2.5, color='grey')
ax.xaxis.set_major_locator(plt.MultipleLocator(5))
ax.set_title('Inmigración de colombianos hacia Canadá\n1980 - 2013',fontsize=18, loc='left')
ax.set_xlabel('Años', fontsize=14)
ax.set_ylabel('Número de inmigrantes', fontsize=14)
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)
ax.grid(linestyle='--')
plt.show()

sudamerica = df.query('Region == "América del Sur"')
  sudamerica.head(10)

colores = ['royalblue', 'orange','forestgreen','orchid',
           'purple','brown','slateblue','gray','olive',
           'navy','teal','tomato']

fig, ax = plt.subplots(figsize=(12,5))

ax.bar(sudamerica.index, sudamerica['Total'],color=colores)
ax.set_title('Inmigracion de sudamericanos hacia Canada\ndurante el periodo de 1980 hasta el 2013',
             loc='left',fontsize=18)
ax.set_xlabel(' ')
ax.set_ylabel('Numero de inmigrantes')
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

plt.show()

colores = ['royalblue', 'orange','forestgreen','orchid',
           'purple','brown','slateblue','gray','olive',
           'navy','teal','tomato']

fig, ax = plt.subplots(figsize=(12,5))

ax.barh(sudamerica.index, sudamerica['Total'],color=colores)
ax.set_title('Inmigracion de sudamericanos hacia Canada\ndurante el periodo de 1980 hasta el 2013',
             loc='left',fontsize=18)
ax.set_ylabel(' ')
ax.set_xlabel('Numero de inmigrantes')
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

plt.show()

sudamerica_sorted = sudamerica.sort_values('Total', ascending=True)
sudamerica_sorted

colores = ['royalblue', 'orange','forestgreen','orchid',
           'purple','brown','slateblue','gray','olive',
           'navy','teal','tomato']

fig, ax = plt.subplots(figsize=(12,5))

ax.barh(sudamerica_sorted.index, sudamerica_sorted['Total'],color=colores)
ax.set_title('Inmigracion de sudamericanos hacia Canada\ndurante el periodo de 1980 hasta el 2013',
             loc='left',fontsize=18)
ax.set_ylabel(' ')
ax.set_xlabel('Numero de inmigrantes')
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

plt.show()

colores = []
for pais in sudamerica_sorted.index:
  if pais == 'Colombia':
    colores.append('forestgreen')
  else:
    colores.append('silver')

fig, ax = plt.subplots(figsize=(12,5))

ax.set_frame_on(False)
ax.xaxis.set_visible(False)
ax.tick_params(axis='y', left=False)

ax.barh(sudamerica_sorted.index, sudamerica_sorted['Total'],color=colores)
ax.set_title('Inmigracion de colombianos hacia Canada\ndurante el periodo de 1980 hasta el 2013',
             loc='left',fontsize=18)
ax.set_ylabel(' ')
ax.yaxis.set_tick_params(labelsize=10)
#ax.set_xlabel('Numero de inmigrantes')
#ax.xaxis.set_tick_params(labelsize=12)


for i,j in enumerate(sudamerica_sorted['Total']):
  ax.text(j+20, i, str(j),color='black',fontsize=8.5, va='center')

fig.savefig('/content/inmigrantes_sudamericanos_canada.png',
            transparent=False,dpi=300,bbox_inches='tight')


plt.show()

print(fig.canvas.get_supported_filetypes())

fig, ax = plt.subplots(figsize=(8,3))
ax.plot(datos_col['Año'], datos_col['Inmigrantes'],lw=2.5, color='grey')
ax.xaxis.set_major_locator(plt.MultipleLocator(5))
ax.set_title('Inmigración de colombianos hacia Canadá\n1980 - 2013',fontsize=18, loc='left')
ax.set_xlabel('Años', fontsize=14)
ax.set_ylabel('Número de inmigrantes', fontsize=14)
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

fig.savefig('/content/inmigrantes_colombianos.png',
            transparent=False,dpi=300,bbox_inches='tight')

plt.show()

"""## **Seaborn**"""

import seaborn as sns

sns.set_theme()

top_10 = df.sort_values('Total', ascending=False).head(10)
top_10

ax = sns.barplot(data=top_10, x='Total', y=top_10.index, orient='h')
ax.set(title='Top 10 paises con mayor migración hacia Canadá\n1980 - 2013',
       xlabel='Numero de Inmigrantes',
       ylabel='Año')
plt.show()

fig, ax = plt.subplots(figsize=(8,3))
ax = sns.barplot(data=top_10, x='Total', y=top_10.index, orient='h')
ax.set_title('Top 10 paises con mayor migracion hacia Canadá\n1980 - 2013',
             loc='left',fontsize=16)
ax.set_xlabel('Numero de Inmigrantes')
ax.set_ylabel(' ')
plt.show()

def generar_grafico(palette):
  fig, ax = plt.subplots(figsize=(8,3))
  ax.set_frame_on(False)
  ax.xaxis.set_visible(False)
  ax.tick_params(axis='y', which='both', size=0)

  ax = sns.barplot(data=top_10, x='Total', y=top_10.index, hue=top_10.index, orient='h',
                   palette=palette,legend=False)
  ax.set_title('Top 10 paises con mayor migracion hacia Canadá\n1980 - 2013',
              loc='left',fontsize=16)
  ax.set_xlabel('Numero de Inmigrantes')
  ax.set_ylabel(' ')

  for i,j in enumerate(top_10['Total']):
    ax.text(j+20, i, str(j),color='black',fontsize=8.5, va='center')


  plt.show()

generar_grafico("rocket")

def generar_grafico(palette):
  fig, ax = plt.subplots(figsize=(8,3))
  ax.set(xticklabels=[])

  ax = sns.barplot(data=top_10, x='Total', y=top_10.index, hue=top_10.index, orient='h',
                   palette=palette,legend=False)
  ax.set_title('Top 10 paises con mayor migracion hacia Canadá\n1980 - 2013',
              loc='left',fontsize=16)
  ax.set_xlabel('Numero de Inmigrantes')
  ax.set_ylabel(' ')

  for i,j in enumerate(top_10['Total']):
    ax.text(j+20, i, str(j),color='black',fontsize=8.5, va='center')


  plt.show()

generar_grafico("rocket")

"""## **Plotly**

https://plotly.com/python/
"""

import plotly.express as px

fig = px.line(datos_col,x='Año',y='Inmigrantes',
              title='Inmigracion de colombianos hacia Canadá entre 1980 y 2013')
fig.update_layout(width=1000,height=500,xaxis={'tickangle':-45},
                  xaxis_title='Año', yaxis_title='Numero de inmigrantes',
                  font_family='Arial', font_size=14, font_color= 'Grey')
fig.show()

sudamerica.head()

sudamerica.drop(['Continente', 'Region', 'Total'],axis=1, inplace =True)
sudamerica

sudamerica = sudamerica.T

sudamerica

fig = px.line(sudamerica,x=sudamerica.index,y=sudamerica.columns,
              title='Inmigracion de sudamericanos hacia Canadá entre 1980 y 2013',
              color= 'Pais', markers=True)
fig.update_layout(width=1000,height=500,xaxis={'tickangle':-45},
                  xaxis_title='Año', yaxis_title='Numero de inmigrantes',
                  font_family='Arial', font_size=14, font_color= 'Grey')

fig.write_html('/content/inmigrantes_sudamericanos.html') #esto para poder exportarlo a un html compartible
fig.show()













